### ISSUE TITLE
Externalize configurations

### ISSUE THREAD

**Issue by cloud-dude** [CloudCredo/graphite-nozzle#3]
We are looking into start contributing to this project.

We aim to create a Bosh release for this piece of software that can be deployed next to a graphite deployment. For this we would like to provide configurations through json or a go config file to graphite-nozzle. We were wondering how would you like us to do this so we can start working on a PR.

any example that you would like us to follow?

@bonzofenix && @cloud-dude

**Comment by teddyking** [comment]
That's great news! Thank you for your interest.

I don't have a particularly strong preference but it probably makes sense to take a similar approach to [datadog-firehose-nozzle](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle) and [varz-firehose-nozzle](https://github.com/cloudfoundry-incubator/varz-firehose-nozzle). I.e. A .json config file that can be passed as an argument on the command line.

Let me know if you need anything else.

Ed

**Comment by teddyking** [comment]
Closing this one off due to PR #4
